### ISSUE TITLE
Compiler not throwing error but plugins are not working

### ISSUE THREAD

**Issue by Hestehviskeren** [iolevel/wpdotnet-sdk#27]
Try any large plugins without PHP Unit test cases and compile it while located in wp-content/plugins.

Activate the plugin and see following:
![bug or what](https://user-images.githubusercontent.com/32708557/55473917-24e58d80-5610-11e9-927d-f2b4844968f0.png)
![no build errors](https://user-images.githubusercontent.com/32708557/55473967-42b2f280-5610-11e9-89d6-98cd374c07e1.png)

This is not just for one plugin; I get this for most plugins I've tested earlier on PHP wordpress(apache hosted); then tried moving them to the wp-content/plugins and recompile solution to then get errors like above when activating.

Is this just me misunderstanding the use of plugins in wpdotnet or is this a known issue?

**Comment by bfistein** [comment]
Hi @Hestehviskeren, thanks for submitting this. It can happen, some exceptions happen during runtime, so that's what you're seeing here. Some plugins use unimplemented functions or extensions as well, and sometimes it's just a simple bug. Will look into this. Since you're saying you tried only large plugins, chances are always higher that there is something we haven't implemented yet.

Besides GDPR and screets-lcx, which plugins did you try? Could you list them please?

**Comment by Hestehviskeren** [comment]
Hi Bfistein, thanks for your answer; I am confused to why I never get an error when compiling? should I not get an error if extensions or unimplemented functions are used?
I tried the following below with similar error:
masterslider
divi-builder
ipanorama
wp-statistics

**Comment by bfistein** [comment]
Thanks. Unimplemented functions would indeed be in the output during compilation. Usually it's just a small bug that happens during runtime when the plugin is activated (or even after that). We're still early in beta, these things will eventually be ironed out. We'll look into this.

**Comment by jakubmisek** [comment]
This issue happens when you activate or use a plugin that was not compiled.
So there is a `.php` file but not compiled - WordPress sees the file, tries to include it, and this happens.
