### ISSUE TITLE
BadImageFormatException when targeting .NET Core 3.0

### ISSUE THREAD

**Issue by bfistein** [iolevel/wpdotnet-sdk#31]
When targeting .NET Core 3.0.100-preview4-011223, the exception below is thrown; works as expected when targeting .NET Core 2.1.

![image](https://user-images.githubusercontent.com/17054650/57180103-b3566480-6e85-11e9-91bb-df1ff1c49dd1.png)

**Comment by RemoOser** [comment]
Have exactly the same issue. Not working for 3.0.100-preview5-011568.

**Comment by jakubmisek** [comment]
thank you, we have to find the IL that the compiler generates causing new .NET JIT to creash.

**Comment by RemoOser** [comment]
Tanks for the message.

I think its maybe easier – just recompile everything (incl php wordpress=>to netcore wordpress ) against the newest preview netcore version. Because netcore 2.1 is a subset of netcore3.0 this should work…

Kind regards

Remo


Von: Jakub Míšek <notifications@github.com>
Gesendet: Freitag, 17. Mai 2019 13:12
An: iolevel/wpdotnet-sdk <wpdotnet-sdk@noreply.github.com>
Cc: Remo Oser <remo.oser@osisa.com>; Comment <comment@noreply.github.com>
Betreff: Re: [iolevel/wpdotnet-sdk] BadImageFormatException when targeting .NET Core 3.0 (#31)


thank you, we have to find the IL that the compiler generates causing new .NET JIT to creash.

**Comment by jakubmisek** [comment]
Yes you are right, we can repro the issue, just didn't find what's wrong yet :) we're pretty excited about possible performance improvements on .NET 3 so looking forward to resolving the issue soon.

**Comment by roberthusak** [comment]
It seems that .NET Core forbids calling interface methods using the ```call``` instruction and requires ```callvirt``` instead (see https://github.com/dotnet/coreclr/issues/24330 and https://github.com/dotnet/coreclr/issues/22407). Previous versions of .NET ignored it and turned it into ```callvirt``` automatically, but now they are probably concerned with the possibility of declaring default method implementations in interfaces.

@jakubmisek I attempted to fix it in https://github.com/peachpiecompiler/peachpie/commit/19c65b5ae18f9b94e7071d746a8f769cc622aa84 (WordPress then worked for me in .NET Core 3.0 preview5), can you please check it and then close this issue once the version is bumped and referenced from here?

**Comment by jakubmisek** [comment]
@roberthusak nice, yes I 've noticed we emit `.call` where we should emit `.callvirt`. Mostly for `IPhpArray`methods within array access and foreach enumeration. Should be fixed there.

**Comment by RemoOser** [comment]
@roberthusak great news - thx for the work. 
Will there be a new package at https://www.nuget.org/packages/PeachPied.WordPress.AspNetCore ?

**Comment by jakubmisek** [comment]
@RemoOser we'll check how it works and prepare the new package as soon as possible : )

**Comment by jakubmisek** [comment]
This exception has been fixed and the update will be released soon. Then there is a redesign of ASP.NET Core response Caching which we have to fix as well. Will create an issue for it.

**Comment by jakubmisek** [comment]
fixed and released :)
