### ISSUE TITLE
Plugins are breaking

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#48]
Most plugins I try to install break. For example I have uploaded a photo of trying to install Duplicate Post plugin:
![Screen Shot 2019-10-07 at 4 20 36 PM](https://user-images.githubusercontent.com/46567272/66345842-db5b5f80-e91e-11e9-80d1-2101ae53d7da.png)

I have tried different versions of php but that didn't help

**Comment by LORDofDOOM** [comment]
@daniel-arrick This happens if you have php files in WP folder that are not compiled, so you only get the string output. If you add a plugin you need to make sure that wp is being recompiled (and the php files are also getting processed)

I use this PeachPied.WordPress.msbuildproj - You'll see that I've modified Compile and Content includes. This works with WooCommerce and BuddyPress for me:

`<Project Sdk="Peachpie.NET.Sdk/0.9.46">
  <Import Project="..\build\Settings.props" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>0e51d101-0992-4aa6-a134-26ea3f2e3934</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <VersionPrefix>$(WordPressVersion)</VersionPrefix>
    
    <NoWarn>PHP0125,PHP5011,PHP6002</NoWarn>
    <Copyright>WordPress</Copyright>
    <Description>WordPress project transformed to managed .NET Standard library.</Description>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php" Exclude="wp-config-sample.php;wp-content/uploads/**;wp-content/plugins/hello.php;wp-content/plugins/akismet/**;wp-content/plugins/buddypress/cli/**;wp-content/plugins/woocommerce/packages/**;wp-content/plugins/woocommerce/src/**;wp-content/plugins/woocommerce/vendor/**;wp-content/plugins/woocommerce/includes/legacy/api/*.php;wp-content/plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php" />
    <Content Include="**;wp-content/plugins/*/*.php" Exclude="**/.git/**;obj/**;bin/**;wp-content/uploads/**;wp-content/plugins/akismet/**;*.msbuildproj" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp3.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="..\PeachPied.WordPress.Sdk\PeachPied.WordPress.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-*" PrivateAssets="All" />
  </ItemGroup>
</Project>`

**Comment by bfistein** [comment]
I was literally just answering, so thanks @LORDofDOOM :) That's right, the plugins need to be compiled as well. Another option is to just use our "deploy to Azure" functionality, where you can install plugins the regular way, because there's a whole process in the background that installs already pre-compiled plugins for you. This option definitely works if you're just trying it out (duplicate post is tested to work afaik).

**Comment by daniel-arrick** [comment]
Thank you this worked like a charm @LORDofDOOM, and thanks for the quick response @bfistein as well
