### ISSUE TITLE
Couldn't deploy to Azure 

### ISSUE THREAD

**Issue by peterturquoise** [iolevel/wpdotnet-sdk#60]
I tried several times his evening to deploy wpdotnet to Azure and it failed every time. I was trying to deploy on F1 on UKSouth. The error was pretty cryptic but hunting don through the Azure logs turned out to be "Error NETSDK1045
The current .NET SDK does not support targeting .NET Core 3.0. Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0." . I'd really like to try your app so is there any way to fix this ? BR Peter

**Comment by jakubmisek** [comment]
It seems not every Azure location supports all the latest .NET Sdks. I've found an interactive map that depicts the current status of available services: https://aspnetcoreon.azurewebsites.net/

Locations not having .NET Core SDK 3.0 won't be able to build the project. If you're using [Azure Deploy] button, you'll probably end up with a screen similar to this:
![image](https://user-images.githubusercontent.com/842150/75036656-a5c0a880-54b2-11ea-84dd-328c5a233c48.png)

Deployment would work on locations having 3.0 SDK.

---

This means the quick deployment option is not available there, but the location would be still able to run the project once it is built elsewhere. For users who do not have an option to use one of the supported locations, the only option is to build first and then deploy the binaries. So this is only for advanced users. Build the project either locally:
```
dotnet publish -c release
```
or on a build server (DevOps, GitHub, ...).

Then deploy the /bin/release/publish to the server. I'm not describing any further steps since it very depends on the actual build server and other credentials.

**Comment by jakubmisek** [comment]
since we're now running on .net 5.0 which should be on all Azure nodes, I'm closing this. Please commend or create a new issue if it happens again.
